
COCO_INSTANCE_CATEGORY_NAMES = [
    "__background__",
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "N/A",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "N/A",
    "backpack",
    "umbrella",
    "N/A",
    "N/A",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "N/A",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "N/A",
    "dining table",
    "N/A",
    "N/A",
    "toilet",
    "N/A",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "N/A",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
]
sysnonyms = {'motorcycle':'motorbike'}
# use yolov5/data/coco.yaml from git clone https://github.com/ultralytics/yolov5

coco80 = [
"person","bicycle","car","motorbike",
"aeroplane","bus","train","truck",
"boat","traffic light","fire hydrant","stop sign",
"parking meter","bench","bird","cat",
"dog","horse","sheep","cow",
"elephant","bear","zebra","giraffe",
"backpack","umbrella","handbag","tie",
"suitcase","frisbee","skis","snowboard",
"sports ball","kite","baseball bat","baseball glove",
"skateboard","surfboard","tennis racket","bottle",
"wine glass","cup","fork","knife",
"spoon","bowl","banana","apple",
"sandwich","orange","broccoli","carrot",
"hot dog","pizza","donut","cake",
"chair","couch","pottedplant","bed",
"diningtable","toilet","tv","laptop",
"mouse","remote","keyboard","cell phone",
"microwave","oven","toaster","sink",
"refrigerator","book","clock","vase",
"scissors","teddy bear","hair drier","toothbrush"
]
